apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.customer.name }}-{{ .Values.product }}
  namespace: customer-{{ .Values.global.customer.name }}
  labels:
    {{- include "singularity.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: singularityhttp
      protocol: TCP
      name: singularityhttp
  selector:
    app: {{ .Values.global.customer.name }}-{{ .Values.product }}
